[package]
name = "custom"
edition.workspace = true

[dependencies]
http-body-util = "0.1.2"
hyper = { version = "1.5.2", features = ["full"] }
hyper-util = { version = "0.1.10", features = ["full"] }
socket2 = "0.5.8"
tokio = { version = "1.43.0", features = ["full"] }
